//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GT_Billing_SystemEntities : DbContext
    {
        public GT_Billing_SystemEntities()
            : base("name=GT_Billing_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<tbl_agent> tbl_agent { get; set; }
        public DbSet<tbl_agent_detail> tbl_agent_detail { get; set; }
        public DbSet<tbl_commercial_product> tbl_commercial_product { get; set; }
        public DbSet<tbl_commercial_produnit> tbl_commercial_produnit { get; set; }
        public DbSet<tbl_commission_detail> tbl_commission_detail { get; set; }
        public DbSet<tbl_commission_master> tbl_commission_master { get; set; }
        public DbSet<tbl_counterreceipt_detail> tbl_counterreceipt_detail { get; set; }
        public DbSet<tbl_counterreceipt_master> tbl_counterreceipt_master { get; set; }
        public DbSet<tbl_customer> tbl_customer { get; set; }
        public DbSet<tbl_invoice_detail> tbl_invoice_detail { get; set; }
        public DbSet<tbl_job_product> tbl_job_product { get; set; }
        public DbSet<tbl_job_produnit> tbl_job_produnit { get; set; }
        public DbSet<tbl_payment_bank> tbl_payment_bank { get; set; }
        public DbSet<tbl_payment_check> tbl_payment_check { get; set; }
        public DbSet<tbl_payment_detail> tbl_payment_detail { get; set; }
        public DbSet<tbl_payment_master> tbl_payment_master { get; set; }
        public DbSet<tbl_payment_pmo> tbl_payment_pmo { get; set; }
        public DbSet<tbl_returnslip_detail> tbl_returnslip_detail { get; set; }
        public DbSet<tbl_returnslip_master> tbl_returnslip_master { get; set; }
        public DbSet<tbl_sales_invoice> tbl_sales_invoice { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<pbcatedt> pbcatedt { get; set; }
        public DbSet<pbcatfmt> pbcatfmt { get; set; }
        public DbSet<pbcatvld> pbcatvld { get; set; }
        public DbSet<tbl_avail_list> tbl_avail_list { get; set; }
        public DbSet<tbl_transactions> tbl_transactions { get; set; }
        public DbSet<vw_job_product_customer> vw_job_product_customer { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<getCustomerDetails_Result> getCustomerDetails(string criteria1, string criteria2, string criteria3)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            var criteria2Parameter = criteria2 != null ?
                new ObjectParameter("criteria2", criteria2) :
                new ObjectParameter("criteria2", typeof(string));
    
            var criteria3Parameter = criteria3 != null ?
                new ObjectParameter("criteria3", criteria3) :
                new ObjectParameter("criteria3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCustomerDetails_Result>("getCustomerDetails", criteria1Parameter, criteria2Parameter, criteria3Parameter);
        }
    
        public virtual ObjectResult<sp_billing_search_customer_Result> sp_billing_search_customer(string criteria1, string criteria2, string criteria3)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            var criteria2Parameter = criteria2 != null ?
                new ObjectParameter("criteria2", criteria2) :
                new ObjectParameter("criteria2", typeof(string));
    
            var criteria3Parameter = criteria3 != null ?
                new ObjectParameter("criteria3", criteria3) :
                new ObjectParameter("criteria3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_billing_search_customer_Result>("sp_billing_search_customer", criteria1Parameter, criteria2Parameter, criteria3Parameter);
        }
    
        public virtual ObjectResult<sp_billing_search_job_product_Result> sp_billing_search_job_product(string criteria1, string criteria2, string criteria3)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            var criteria2Parameter = criteria2 != null ?
                new ObjectParameter("criteria2", criteria2) :
                new ObjectParameter("criteria2", typeof(string));
    
            var criteria3Parameter = criteria3 != null ?
                new ObjectParameter("criteria3", criteria3) :
                new ObjectParameter("criteria3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_billing_search_job_product_Result>("sp_billing_search_job_product", criteria1Parameter, criteria2Parameter, criteria3Parameter);
        }
    
        public virtual ObjectResult<sp_billing_search_commercial_product_Result> sp_billing_search_commercial_product(string criteria1, string criteria2, string criteria3)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            var criteria2Parameter = criteria2 != null ?
                new ObjectParameter("criteria2", criteria2) :
                new ObjectParameter("criteria2", typeof(string));
    
            var criteria3Parameter = criteria3 != null ?
                new ObjectParameter("criteria3", criteria3) :
                new ObjectParameter("criteria3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_billing_search_commercial_product_Result>("sp_billing_search_commercial_product", criteria1Parameter, criteria2Parameter, criteria3Parameter);
        }
    
        public virtual int sp_billing_delete_commercial_product(string criteria1)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_billing_delete_commercial_product", criteria1Parameter);
        }
    
        public virtual int sp_billing_commercial_product_delete(string criteria1)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_billing_commercial_product_delete", criteria1Parameter);
        }
    
        public virtual int sp_billing_commercial_product_update(string code, string description, Nullable<decimal> unit_price, Nullable<decimal> unit_pricekg, Nullable<decimal> unit_pricepck, Nullable<decimal> unit_priceth)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var unit_priceParameter = unit_price.HasValue ?
                new ObjectParameter("unit_price", unit_price) :
                new ObjectParameter("unit_price", typeof(decimal));
    
            var unit_pricekgParameter = unit_pricekg.HasValue ?
                new ObjectParameter("unit_pricekg", unit_pricekg) :
                new ObjectParameter("unit_pricekg", typeof(decimal));
    
            var unit_pricepckParameter = unit_pricepck.HasValue ?
                new ObjectParameter("unit_pricepck", unit_pricepck) :
                new ObjectParameter("unit_pricepck", typeof(decimal));
    
            var unit_pricethParameter = unit_priceth.HasValue ?
                new ObjectParameter("unit_priceth", unit_priceth) :
                new ObjectParameter("unit_priceth", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_billing_commercial_product_update", codeParameter, descriptionParameter, unit_priceParameter, unit_pricekgParameter, unit_pricepckParameter, unit_pricethParameter);
        }
    
        public virtual ObjectResult<sp_billing_search_agent_Result> sp_billing_search_agent(string criteria1, string criteria2, string criteria3)
        {
            var criteria1Parameter = criteria1 != null ?
                new ObjectParameter("criteria1", criteria1) :
                new ObjectParameter("criteria1", typeof(string));
    
            var criteria2Parameter = criteria2 != null ?
                new ObjectParameter("criteria2", criteria2) :
                new ObjectParameter("criteria2", typeof(string));
    
            var criteria3Parameter = criteria3 != null ?
                new ObjectParameter("criteria3", criteria3) :
                new ObjectParameter("criteria3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_billing_search_agent_Result>("sp_billing_search_agent", criteria1Parameter, criteria2Parameter, criteria3Parameter);
        }
    }
}
