//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_delivery_detail
    {
        public long detail_id { get; set; }
        public long control_no { get; set; }
        public long customer_id { get; set; }
        public Nullable<long> bdls { get; set; }
        public Nullable<long> pcks { get; set; }
        public decimal weight { get; set; }
        public long delivery_id { get; set; }
        public string control_type { get; set; }
        public string control_cat { get; set; }
        public Nullable<long> rolls { get; set; }
        public string status { get; set; }
    
        public virtual tbl_delivery_master tbl_delivery_master { get; set; }
    }
}
