//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sales_invoice
    {
        public long si_no { get; set; }
        public string si_type { get; set; }
        public string invoice_id { get; set; }
        public string control_no { get; set; }
        public long customer_id { get; set; }
        public string po_no { get; set; }
        public string sales_area { get; set; }
        public string terms { get; set; }
        public System.DateTime si_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string status { get; set; }
        public string via { get; set; }
        public string vessel { get; set; }
        public string vge_no { get; set; }
        public string bill_no { get; set; }
        public decimal freight { get; set; }
        public decimal handling { get; set; }
        public decimal ppa { get; set; }
        public decimal subtotal { get; set; }
        public decimal tax { get; set; }
        public decimal totalamount { get; set; }
        public string agent_code { get; set; }
        public decimal agent_percent { get; set; }
        public decimal agent_commission { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public string adjustment_type { get; set; }
        public string dr_no_copy { get; set; }
    }
}
