//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_requisition_detail
    {
        public long rf_detail_id { get; set; }
        public long rf_id { get; set; }
        public long rf_no { get; set; }
        public long item_id { get; set; }
        public long qty { get; set; }
        public string unit { get; set; }
        public string description { get; set; }
        public long pcsperpack { get; set; }
        public long remqty { get; set; }
        public long overqty { get; set; }
        public string status { get; set; }
    }
}
