//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_return_packing
    {
        public long ret_packing_id { get; set; }
        public long ret_detail_id { get; set; }
        public string code { get; set; }
        public long qtyinpcs { get; set; }
        public decimal qtyinkgs { get; set; }
        public string description { get; set; }
        public long packing_id { get; set; }
        public decimal unit_price { get; set; }
        public decimal amount { get; set; }
        public Nullable<long> qtyinrolls { get; set; }
    
        public virtual tbl_return_detail tbl_return_detail { get; set; }
    }
}
