//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_control_local_detail
    {
        public tbl_control_local_detail()
        {
            this.tbl_control_local_packing = new HashSet<tbl_control_local_packing>();
        }
    
        public string item_code { get; set; }
        public long control_no { get; set; }
        public long qty { get; set; }
        public string unit { get; set; }
        public string description { get; set; }
        public string control_type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual tbl_control_local_master tbl_control_local_master { get; set; }
        public virtual ICollection<tbl_control_local_packing> tbl_control_local_packing { get; set; }
    }
}
