//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer_temp
    {
        public long customer_id { get; set; }
        public string customer_name { get; set; }
        public string contact_person { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public string fax_no { get; set; }
        public string email_add { get; set; }
        public string status { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> over_ { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<int> credit_terms { get; set; }
    }
}
