//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transactions
    {
        public int trans_id { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string trans_name { get; set; }
        public string trans_number { get; set; }
        public string trans_type { get; set; }
        public string user_name { get; set; }
        public string trans_action { get; set; }
    }
}
