//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_holdjoborder
    {
        public long id { get; set; }
        public string type { get; set; }
        public string job_type { get; set; }
        public long jo_no { get; set; }
        public int customer_id { get; set; }
        public string product_code { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string released_by { get; set; }
    }
}
