//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agent
    {
        public int id { get; set; }
        public string agent_name { get; set; }
        public string agent_code { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public string email_add { get; set; }
        public string status { get; set; }
        public decimal commission { get; set; }
    }
}
