//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_laminated_design
    {
        public long design_id { get; set; }
        public string design_code { get; set; }
        public string prod_code { get; set; }
        public string description { get; set; }
        public Nullable<long> bottom_fold { get; set; }
        public Nullable<long> left_fold { get; set; }
        public Nullable<long> right_fold { get; set; }
        public Nullable<long> inner_dim_width { get; set; }
        public Nullable<long> inner_dim_length { get; set; }
        public Nullable<long> outer_dim_width { get; set; }
        public Nullable<long> outer_dim_length { get; set; }
        public Nullable<long> no_of_colors { get; set; }
        public string front_print { get; set; }
        public string back_print { get; set; }
        public string sealing_type { get; set; }
        public string opening_portion { get; set; }
        public Nullable<long> top_seal_width { get; set; }
        public Nullable<long> bottom_seal_width { get; set; }
        public Nullable<long> side_seal_width { get; set; }
        public Nullable<long> center_seal_width { get; set; }
        public string tear_knotch { get; set; }
        public string punch_whole { get; set; }
        public string status { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string print_style { get; set; }
        public Nullable<System.DateTime> design_date { get; set; }
    }
}
