//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_return_master
    {
        public tbl_return_master()
        {
            this.tbl_return_detail = new HashSet<tbl_return_detail>();
        }
    
        public long rs_no { get; set; }
        public long control_no { get; set; }
        public string po_no { get; set; }
        public string invoice_no { get; set; }
        public long customer_id { get; set; }
        public string control_category { get; set; }
        public System.DateTime date_returned { get; set; }
        public string notes { get; set; }
        public string control_type { get; set; }
        public string return_slip_no { get; set; }
        public Nullable<System.DateTime> control_date { get; set; }
    
        public virtual ICollection<tbl_return_detail> tbl_return_detail { get; set; }
    }
}
