//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_return_detail
    {
        public tbl_return_detail()
        {
            this.tbl_return_packing = new HashSet<tbl_return_packing>();
        }
    
        public long ret_detail_id { get; set; }
        public long rs_no { get; set; }
        public long qty { get; set; }
        public string unit { get; set; }
        public string item_code { get; set; }
        public string control_type { get; set; }
        public string description { get; set; }
    
        public virtual tbl_return_master tbl_return_master { get; set; }
        public virtual ICollection<tbl_return_packing> tbl_return_packing { get; set; }
    }
}
