//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment_pmo
    {
        public string bank_name { get; set; }
        public string branch { get; set; }
        public string acct_no { get; set; }
        public System.DateTime pmo_date { get; set; }
        public long payment_id { get; set; }
        public string status { get; set; }
    
        public virtual tbl_payment_bank tbl_payment_bank { get; set; }
    }
}
