//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_requisition_master
    {
        public long rf_id { get; set; }
        public long rf_no { get; set; }
        public string rf_type { get; set; }
        public string po_no { get; set; }
        public long po_id { get; set; }
        public System.DateTime po_date { get; set; }
        public long customer_id { get; set; }
        public string status { get; set; }
        public string requiested_by { get; set; }
        public string approved_by { get; set; }
        public string remarks { get; set; }
    }
}
