//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_control_local_master
    {
        public tbl_control_local_master()
        {
            this.tbl_control_local_detail = new HashSet<tbl_control_local_detail>();
        }
    
        public long control_no { get; set; }
        public System.DateTime control_date { get; set; }
        public long customer_id { get; set; }
        public string order_no { get; set; }
        public string po_no { get; set; }
        public string truck_no { get; set; }
        public string status { get; set; }
        public string control_type { get; set; }
        public string notes { get; set; }
        public string trip { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual ICollection<tbl_control_local_detail> tbl_control_local_detail { get; set; }
    }
}
