//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment_master
    {
        public long or_no { get; set; }
        public string or_type { get; set; }
        public System.DateTime or_date { get; set; }
        public long payment_id { get; set; }
        public long customer_id { get; set; }
        public string payment_form { get; set; }
        public decimal amount { get; set; }
        public string status { get; set; }
        public decimal amt_applied { get; set; }
    }
}
