//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_returnslip_detail
    {
        public long item_no { get; set; }
        public long rs_no { get; set; }
        public decimal qty { get; set; }
        public string unit { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public decimal disc { get; set; }
        public decimal amount { get; set; }
        public string category { get; set; }
        public string status { get; set; }
    
        public virtual tbl_returnslip_master tbl_returnslip_master { get; set; }
    }
}
