//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_returnslip_master
    {
        public tbl_returnslip_master()
        {
            this.tbl_returnslip_detail = new HashSet<tbl_returnslip_detail>();
        }
    
        public long rs_no { get; set; }
        public long si_no { get; set; }
        public long customer_id { get; set; }
        public System.DateTime rs_date { get; set; }
        public decimal totalamount { get; set; }
        public string notes { get; set; }
        public string si_type { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<tbl_returnslip_detail> tbl_returnslip_detail { get; set; }
    }
}
