//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_counterreceipt_master
    {
        public tbl_counterreceipt_master()
        {
            this.tbl_counterreceipt_detail = new HashSet<tbl_counterreceipt_detail>();
        }
    
        public long cr_no { get; set; }
        public long customer_id { get; set; }
        public System.DateTime cr_date { get; set; }
        public string status { get; set; }
        public decimal totalamount { get; set; }
        public string agent_code { get; set; }
        public string notes { get; set; }
    
        public virtual ICollection<tbl_counterreceipt_detail> tbl_counterreceipt_detail { get; set; }
    }
}
