//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_polybags_jo
    {
        public long jo_no { get; set; }
        public System.DateTime jo_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public long customer_id { get; set; }
        public string po_no { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string ptype { get; set; }
        public string plastic_color { get; set; }
        public Nullable<decimal> bottom_fold { get; set; }
        public Nullable<decimal> left_fold { get; set; }
        public Nullable<decimal> right_fold { get; set; }
        public decimal width { get; set; }
        public decimal length { get; set; }
        public Nullable<decimal> thickness_single { get; set; }
        public Nullable<decimal> thickness_tube { get; set; }
        public Nullable<decimal> thickness_fold { get; set; }
        public Nullable<decimal> weight_per_pc { get; set; }
        public string checking_based { get; set; }
        public string plastic_type { get; set; }
        public string plastic_category { get; set; }
        public string print_style { get; set; }
        public long no_of_colors { get; set; }
        public string front_print { get; set; }
        public string back_print { get; set; }
        public decimal ordered_qty { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> inputted_qty { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
        public Nullable<long> changespecs_no { get; set; }
        public string created_by { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_last_edit { get; set; }
        public string product_category { get; set; }
        public string approved_by { get; set; }
        public string verified_by { get; set; }
        public string noted_by { get; set; }
        public string approved_path { get; set; }
        public string verified_path { get; set; }
        public string noted_path { get; set; }
        public string prepared_path { get; set; }
        public string order_status { get; set; }
        public Nullable<long> invoice_no { get; set; }
        public string plate_no { get; set; }
        public string revision_code { get; set; }
        public string prod_code { get; set; }
        public Nullable<System.DateTime> date_faxed { get; set; }
    }
}
