//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_control_local_packing
    {
        public long packing_id { get; set; }
        public string item_code { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public long qtyinpcs { get; set; }
        public decimal qtyinkgs { get; set; }
        public string status { get; set; }
        public string order_no { get; set; }
        public Nullable<long> qtyinrolls { get; set; }
    
        public virtual tbl_control_local_detail tbl_control_local_detail { get; set; }
    }
}
