//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_control_summary
    {
        public System.DateTime control_date { get; set; }
        public long total_bdls { get; set; }
        public long total_rolls { get; set; }
        public long total_pcks { get; set; }
        public long total_kgs { get; set; }
        public string category { get; set; }
    }
}
