//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment_bank
    {
        public tbl_payment_bank()
        {
            this.tbl_payment_check = new HashSet<tbl_payment_check>();
            this.tbl_payment_pmo = new HashSet<tbl_payment_pmo>();
        }
    
        public string bank_name { get; set; }
        public string branch { get; set; }
    
        public virtual ICollection<tbl_payment_check> tbl_payment_check { get; set; }
        public virtual ICollection<tbl_payment_pmo> tbl_payment_pmo { get; set; }
    }
}
