//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_polybags_design
    {
        public long design_id { get; set; }
        public string design_code { get; set; }
        public string prod_code { get; set; }
        public string description { get; set; }
        public string ptype { get; set; }
        public string plastic_color { get; set; }
        public Nullable<long> bottom_fold { get; set; }
        public Nullable<long> left_fold { get; set; }
        public Nullable<long> right_fold { get; set; }
        public Nullable<long> width { get; set; }
        public Nullable<long> length { get; set; }
        public string print_style { get; set; }
        public Nullable<long> no_of_colors { get; set; }
        public string front_print { get; set; }
        public string back_print { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<System.DateTime> design_date { get; set; }
    }
}
