//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public string code { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string acc_level { get; set; }
        public int access { get; set; }
        public string img { get; set; }
        public string signature_path { get; set; }
        public Nullable<long> width { get; set; }
        public Nullable<long> height { get; set; }
        public Nullable<long> y { get; set; }
    }
}
