//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_Order_Monitoring_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_counterreceipt_detail
    {
        public long invoice_id { get; set; }
        public long cr_no { get; set; }
        public long si_no { get; set; }
        public string si_type { get; set; }
        public System.DateTime si_date { get; set; }
        public string particulars { get; set; }
        public string satus { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public decimal total { get; set; }
    
        public virtual tbl_counterreceipt_master tbl_counterreceipt_master { get; set; }
    }
}
